name: 'Chormatic Deployment'
on:
  pull_request:
    branches: [dev, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: yarn install
        run: yarn install
      - name: build storybook
        run: yarn build-storybook
      - name: upload to chromatic
        run: yarn chromatic --project-token=${{secrets.CHROMATIC_TOKEN}}
