name: 'Chormatic Deployment'
on:
  pull_request:
    branches: [dev, master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: version check
        run: node -v; yarn --version;
      - name: yarn install
        run: yarn install
      - name: build storybook
        run: yarn build-storybook
      - name: upload to chromatic
        run: yarn chromatic --project-token=${{secrets.CHROMATIC_TOKEN}}
